
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND EQUALS GREATER IDENTIFIER IF LBRACE LESS LPAREN NOT NUMBER OPERATOR OR RBRACE RPAREN\n    expression : expression EQUALS expression\n               | expression LESS expression\n               | expression GREATER expression\n               | expression AND expression\n               | expression OR expression\n               | NOT expression\n               | IDENTIFIER\n               | NUMBER\n    statement : IF LPAREN expression RPAREN LBRACE statements RBRACE\n                | assignment\n                | array_usagestatements : statement\n                  | statements statementassignment : IDENTIFIER EQUALS expressionarray_usage : IDENTIFIER LBRACE expression RBRACE'
    
_lr_action_items = {'NOT':([0,2,5,6,7,8,9,],[2,2,2,2,2,2,2,]),'IDENTIFIER':([0,2,5,6,7,8,9,],[3,3,3,3,3,3,3,]),'NUMBER':([0,2,5,6,7,8,9,],[4,4,4,4,4,4,4,]),'$end':([1,3,4,10,11,12,13,14,15,],[0,-7,-8,-6,-1,-2,-3,-4,-5,]),'EQUALS':([1,3,4,10,11,12,13,14,15,],[5,-7,-8,5,5,5,5,5,5,]),'LESS':([1,3,4,10,11,12,13,14,15,],[6,-7,-8,6,6,6,6,6,6,]),'GREATER':([1,3,4,10,11,12,13,14,15,],[7,-7,-8,7,7,7,7,7,7,]),'AND':([1,3,4,10,11,12,13,14,15,],[8,-7,-8,8,8,8,8,8,8,]),'OR':([1,3,4,10,11,12,13,14,15,],[9,-7,-8,9,9,9,9,9,9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,5,6,7,8,9,],[1,10,11,12,13,14,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression EQUALS expression','expression',3,'p_expression','Sentencia_IF.py',49),
  ('expression -> expression LESS expression','expression',3,'p_expression','Sentencia_IF.py',50),
  ('expression -> expression GREATER expression','expression',3,'p_expression','Sentencia_IF.py',51),
  ('expression -> expression AND expression','expression',3,'p_expression','Sentencia_IF.py',52),
  ('expression -> expression OR expression','expression',3,'p_expression','Sentencia_IF.py',53),
  ('expression -> NOT expression','expression',2,'p_expression','Sentencia_IF.py',54),
  ('expression -> IDENTIFIER','expression',1,'p_expression','Sentencia_IF.py',55),
  ('expression -> NUMBER','expression',1,'p_expression','Sentencia_IF.py',56),
  ('statement -> IF LPAREN expression RPAREN LBRACE statements RBRACE','statement',7,'p_statement','Sentencia_IF.py',65),
  ('statement -> assignment','statement',1,'p_statement','Sentencia_IF.py',66),
  ('statement -> array_usage','statement',1,'p_statement','Sentencia_IF.py',67),
  ('statements -> statement','statements',1,'p_statements','Sentencia_IF.py',76),
  ('statements -> statements statement','statements',2,'p_statements','Sentencia_IF.py',77),
  ('assignment -> IDENTIFIER EQUALS expression','assignment',3,'p_assignment','Sentencia_IF.py',89),
  ('array_usage -> IDENTIFIER LBRACE expression RBRACE','array_usage',4,'p_array_usage','Sentencia_IF.py',95),
]
